# Generated by Django 4.2.6 on 2023-11-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviews', '0003_review_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
    ]
